#!/bin/bash

# 包依赖 jq bat

# 设置API
URL="https://api.openai.com/v1/chat/completions"
API_KEY=""
ENGINE="gpt-3.5-turbo"

[[ -z $API_KEY ]] && echo -e "Set your API_KEY" && exit 1

# Chat 模型参数设置
TEMPERATURE="0.7"
TOP_P="1"
FREQUENCY_PENALTY="0.81"
PRESENCE_PENALTY="0.8"

echo -e "Exit with \033[36mq\033[0m."
running=true

# 错误info
Error() {
    if echo "$1" | jq -e '.error' >/dev/null; then
        echo -e "Error, you can try again\033[0;31m$(echo "$1" | jq -r '.error.type')\033[0m"
        exit 1
    fi
}

gptlog=""
while $running; do
    echo -e "User: "
    read -r prompt
    if [ "$prompt" == "q" ]; then
        exit 0
        # 输入jp: 翻译成日语
    elif [[ "$prompt" =~ ^jp: ]]; then
        input=$(echo "$prompt" | grep -oP 'jp: \K.*')
        content="{\"role\": \"system\", \"content\": \"You are a translator. Translate all text to japanese.\"}, {\"role\": \"user\", \"content\": \"$input\"},"
        # 输入en: 翻译成英文
    elif [[ "$prompt" =~ ^en: ]]; then
        input=$(echo "$prompt" | grep -oP 'en: \K.*')
        content="{\"role\": \"system\", \"content\": \"You are a translator. Translate all text to english.\"}, {\"role\": \"user\", \"content\": \"$input\"},"
        # 输入cn: 翻译成中文
    elif [[ "$prompt" =~ ^cn: ]]; then
        input=$(echo "$prompt" | grep -oP 'cn: \K.*')
        content="{\"role\": \"system\", \"content\": \"You are a senior programmer. Translate all text to chinese.\"}, {\"role\": \"user\", \"content\": \"$input\"},"
    elif [[ "$prompt" =~ ^code: ]]; then
        input=$(echo "$prompt" | grep -oP 'code: \K.*')
        gptlog+="User: $input\n"
        format_gptlog=$(echo "$gptlog" | sed -z 's/\n/\\n/g')
        content="{\"role\": \"system\", \"content\": \"You are a senior programmer. Answer only with the code fence. Do not write explanations.\"}, {\"role\": \"user\", \"content\": \"$format_gptlog\"},"
    elif [[ "$prompt" =~ ^ee ]]; then
        $EDITOR "$RESULT"
        running=false
        exit 0
        # 通用
    else
        input="$prompt"
        gptlog+="User: $input\n"
        format_gptlog=$(echo "$gptlog" | sed -z 's/\n/\\n/g')
        content="{\"role\": \"system\", \"content\": \"YYou are now chatting with an AI assistant. Ask any questions you have!\"}, {\"role\": \"user\", \"content\": \"$format_gptlog\"},"
    fi

    raw_response=$(
        curl -s -X POST $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d "{\"model\": \"$ENGINE\", \"messages\": [${content%?}], \"temperature\": $TEMPERATURE, \"top_p\": $TOP_P, \"frequency_penalty\": $FREQUENCY_PENALTY, \"presence_penalty\": $PRESENCE_PENALTY}"
    )

    Error "$raw_response"
    format_response=$(echo "$raw_response" | jq -r '.choices[0].message.content' | awk '{$1=$1};1')
    echo -e "\n\033[36mChatGPT: \033[0m\n"
    echo "$format_response" | bat --plain --color=always --language=markdown
    gptlog+="ChatGPT: $format_response\n"
done
